export const FETCHING_ITEMS_SUCCESS = 'FETCHING_ITEMS_SUCCESS'
export const FETCHING_ITEM = 'FETCHING_ITEM'
export const FETCHING_ITEM_SUCCESS = 'FETCHING_ITEM_SUCCESS'
export const FETCHING_META_SUCCESS = 'FETCHING_META_SUCCESS'
export const FETCHING_PAGINATION_SUCCESS = 'FETCHING_PAGINATION_SUCCESS'

export const CREATING_ITEM_SUCCESS = 'CREATING_ITEM_SUCCESS'
export const UPDATING_ITEM_SUCCESS = 'UPDATING_ITEM_SUCCESS'
export const DELETING_ITEM_SUCCESS = 'DELETING_ITEM_SUCCESS'

export const LOADING_START = 'LOADING_START'
export const LOADING_SUCCESS = 'LOADING_SUCCESS'
export const LOADING_FAILURE = 'LOADING_FAILURE'
export const LOADING_PROGRESS = 'LOADING_PROGRESS'

export const CLEAR = 'CLEAR'
export const CLEAR_ERROR = 'CLEAR_ERROR'